#!/bin/bash

# if ! [ -e /dev/console ] ; then
#     socat -u pty,link=/dev/console stdout &
# fi

# socat -u pty,link=/dev/console stdout &

#! /bin/bash
export CONSOLE_FD
exec {CONSOLE_FD}<> /dev/console

exec /sbin/init "$@"
